<a href="https://colab.research.google.com/github/jerrycheewy/aRticles/blob/master/Learn_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Popular libraries

## NumPy

In [0]:
import numpy as np

In [0]:
# integer array
np.array([1,2,3.5])

array([1. , 2. , 3.5])

### Helper functions to create dummy arrays

In [0]:
# 1-d array of zeros
np.zeros(5)

NameError: ignored

In [0]:
# N x M matrix of ones
np.ones(shape = (3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
# N x M matrix of a particular value
np.full(shape = (3,3), fill_value = 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [0]:
# Sequence of numbers
np.arange(start = 0, stop = 10, step = 1) #Stop inclusive!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# Linearly spaced numbers
np.linspace(start = 0, stop = 1, num = 5) #Stop is inclusive here!

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
# N x M matrix of uniformly random numbers
np.random.random(size = (2,3))

array([[0.71122616, 0.88684375, 0.43638226],
       [0.99853045, 0.65938549, 0.35517915]])

In [0]:
# N x M matrix of normally distributed random values
np.random.normal(size = (2,3), loc = 0, scale = 1) #mean 0, SD 1

array([[ 0.04360631,  1.88184806,  1.04853842],
       [ 0.48709372,  1.81523993, -0.48672449]])

In [0]:
# N x M random integers
np.random.randint(size = (2,3), low = 0, high = 10)

array([[2, 3, 5],
       [3, 9, 3]])

In [0]:
# Identity matrix
np.eye(N = 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array attributes

In [0]:
a1 = np.random.randint(size = (3,3), low = 0, high = 10)
print(a1.ndim)
print(a1.shape)
print(a1.dtype)

2
(3, 3)
int64


In [0]:
print(a1.itemsize)
print(a1.size)
print(a1.nbytes)
a1.itemsize * a1.size == a1.nbytes

8
9
72


True

### Subsetting arrays

In [0]:
a1

array([[0, 9, 0],
       [7, 2, 5],
       [7, 0, 2]])

In [0]:
a1[0,0] #Row 1 Col 1

0

In [0]:
a1[-1,-1] #Last row, Last col (negative indexing)

2

In [0]:
a1[0,0] = 999 #Overwrite a cell
a1

array([[999,   9,   0],
       [  7,   2,   5],
       [  7,   0,   2]])

In [0]:
#Overwriting an element is subject to the dtype of the array
#In this case, a1 is an integer array, so inserting a float will faill
a1[0,0] = 9.99
a1

array([[9, 9, 0],
       [7, 2, 5],
       [7, 0, 2]])

In [0]:
#Slice a chunk of the array
a2 = np.arange(0, 10, 1)
a2[:3] #First item to the 3rd item (Python indexing starts from 0, R uses 1!)

array([0, 1, 2])

In [0]:
# Every other element
a2[::2]

array([0, 2, 4, 6, 8])

In [0]:
# Every other element, starting from index 2
a2[2::5]

array([2, 7])

### Array object manipulation

In [0]:
# Copy array
a3 = a2.copy() #copy is a method, not an object attribute, so use parentheses at the end!
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [0]:
# Reshaping the array
a4 = a1.reshape((1,9))
print(a1)
print(a4)

[[9 9 0]
 [7 2 5]
 [7 0 2]]
[[9 9 0 7 2 5 7 0 2]]


In [0]:
# Join (Concatenate) Arrays
a5 = np.arange(1,11)
a6 = np.arange(11,21)
print(a5)
print(a6)
np.concatenate([a5, a6, a6, a5]) #In Python, a 'list' is put together with square brackets, in R we typically use c()
np.concatenate([a5, a6, a6, a5]).reshape((5,8)) #Combine concatenation with a reshape

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20,  1,  2],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [0]:
# Split arrays
a7 = np.concatenate([a5, a6])
print(a7.shape)
a71, a72, a73 = np.split(a7, [5,10]) #Specify split-points
print(a71, a72, a73)

(20,)
[1 2 3 4 5] [ 6  7  8  9 10] [11 12 13 14 15 16 17 18 19 20]


In [0]:
# Split N x M array
a8 = np.arange(1,10,1).reshape((3,3))
print(a8)
# Split first two rows and last row
print(np.vsplit(a8, [2]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


### Vectorized computations with native arithmetic operators

The use of these are nearly identical to that in R, except for the specification of the library numpy in front of functions.

In [0]:
# Like R, its best to make use of the vectorized nature of Python's native arithmetic operators
print(a8)
print(a8 * 3)
print(a8 ** 2) #Each element to the power of 2
print(a8 / 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [0]:
# Logarithms
print(np.log(np.exp(1)))
print(np.log10(100))

1.0
2.0


In [0]:
# Specifying output location even within the np function
a9 = np.arange(5)
a10 = np.zeros(10)
print(a9)
print(a10)
np.multiply(a9, 2, out = a10[::2]) #Multiply every element in a9 by 2, insert into every other element in a10
print(a10) #See how the results are inserted into a10

[0 1 2 3 4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 0. 4. 0. 6. 0. 8. 0.]


### Aggregation functions

In [0]:
agg1 = np.random.normal(0,1,100)
#NumPy functions are executed in compiled code, so it is faster than base Python `sum`
%timeit(sum(agg1))
%timeit(np.sum(agg1))

The slowest run took 4.04 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 16.5 µs per loop
The slowest run took 15.25 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.84 µs per loop


In [0]:
# Different syntax, the first is closer to R where it takes a form of a function
print(np.min(agg1))
print(agg1.min())

-2.4196589409864964
-2.4196589409864964


In [0]:
# Aggregation across a row or column for M x N array
agg2 = np.random.random(9).reshape((3,3))
print(agg2)
np.min(agg2, axis = 0) # 0 for column and 1 for row. This is opposite to R's row by col notation.

[[0.9942981  0.37818075 0.60262291]
 [0.32788228 0.39151336 0.32985034]
 [0.77227162 0.05002726 0.50186952]]


array([0.32788228, 0.05002726, 0.32985034])

In [0]:
# Aggregation with missing values
# In R we handle these with the argument `na.rm = TRUE`
# In Python we have to use NaN functions to cater for the presence missing values
agg3 = np.array([np.nan, 1, 2])
print(agg3)
print(np.sum(agg3))
print(np.nansum(agg3))

[nan  1.  2.]
nan
3.0


In [0]:
import pandas as pd

In [0]:
height = pd.read_csv('https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/data/president_heights.csv')

In [0]:
height.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [0]:
#Basic statistics computation
print(np.mean(height['height(cm)'])) # OR
print(height['height(cm)'].mean())
print(np.std(height['height(cm)'])) #R uses sd() instead
print(np.percentile(height['height(cm)'], 50))
print(np.median(height['height(cm)']))  

179.73809523809524
179.73809523809524
6.931843442745893
182.0
182.0


### Using Booleans

In [0]:
boo1 = np.random.randint(0,10, (5,5))
print(boo1)
print(boo1 < 5)

[[9 4 7 3 0]
 [2 7 3 4 7]
 [3 6 7 8 0]
 [4 8 5 2 0]
 [7 5 9 7 0]]
[[False  True False  True  True]
 [ True False  True  True False]
 [ True False False False  True]
 [ True False False  True  True]
 [False False False False  True]]


In [0]:
# You can also perform arithmetic using booleans directly, without the need to subset first
# In R we would've written a longer line with base R like so - sum(boo1[boo1 < 5])
np.sum(boo1 < 5)
# You can even specify whether the computation is to be done via row or column
print(np.sum(boo1 < 5, axis = 0)) #1 for Row (remember - opposite to R!)

[3 1 1 3 4]


In [0]:
# Counting elements that meet criteria
print(np.count_nonzero(boo1 < 5))
print(np.count_nonzero(boo1 < 5, axis = 0))

# Just to check if TRUE/FALSE
print(np.any(boo1 == 5, axis = 0))
print(np.all(boo1 == 5, axis = 0))

12
[3 1 1 3 4]
[False  True  True False False]
[False False False False False]


In [0]:
# Combining boolean operators. Make sure to use parentheses properly.
print(np.sum((boo1 > 1) & (boo1 < 5)))

# Python uses `~` to denote negative selection while R uses `!`
print(np.sum(~((boo1 <= 1) | (boo1 >= 5))))

8
8


In [0]:
# Using boolean for indexing. This technique is known as masking.
print(boo1)
print(boo1[boo1 > 5])

[[9 4 7 3 0]
 [2 7 3 4 7]
 [3 6 7 8 0]
 [4 8 5 2 0]
 [7 5 9 7 0]]
[9 7 7 7 6 7 8 8 7 9 7]


### Fancy indexing
This section is pretty cool, I have not encountered such a technique in R.

In [0]:
# You can pass your index with a shape, to ensure that the output returns in the same shape.
boo2 = np.arange(1,11,1)
print(boo2)
boo2_ind = np.array([[0,1],[2,3]]) #Select elements 1-4 with a 2x2 shape
print(boo2[boo2_ind])

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2]
 [3 4]]


In [0]:
# Overwrite array elements with indexing
print(boo2)
boo2_ind2 = np.array([1,2,3])
boo2[boo2_ind2] = 9999
print(boo2)

[ 1  2  3  4  5  6  7  8  9 10]
[   1 9999 9999 9999    5    6    7    8    9   10]


### Sorting Arrays

In [0]:
sort1 = np.array(["hello","world","abc"])
print(sort1)

['hello' 'world' 'abc']


In [0]:
np.sort(sort1)

array(['abc', 'hello', 'world'], dtype='<U5')

In [0]:
sort2 = np.random.randint(0,100,10)
print(sort2)
np.sort(sort2)

[25 33 33 89 85 86 34 46 26 18]


array([18, 25, 26, 33, 33, 34, 46, 85, 86, 89])

## Pandas

In [0]:
import pandas as pd
pd.__version__

'1.0.3'

### Pandas Series
A Pandas `Series` is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [0]:
series1 = pd.Series([1,2,3.5])
print(series1)
# A Pandas Series contains an Index and the Values
print(series1.values)
print(series1.index)

0    1.0
1    2.0
2    3.5
dtype: float64
[1.  2.  3.5]
RangeIndex(start=0, stop=3, step=1)


In [0]:
# Indexing is the same as a NumPy array
print(series1[0:2])

# If you provide a custom index, you can use that too
series2 = pd.Series([11,12,13], index = ["a","b","c"])
print(series2["b"])

0    1.0
1    2.0
dtype: float64
12


In [0]:
# Create a Series from a dictionary
# Dictionary is a key/index : value pair
series3 = pd.Series(
    {'Andrew' : 90,
     'Bryan' : 91,
     'Charles' : 95}
)
print(series3)

# The only difference is that a Series can be sliced like an Array
series3['Andrew':'Bryan']

Andrew     90
Bryan      91
Charles    95
dtype: int64


Andrew    90
Bryan     91
dtype: int64

### Pandas DataFrame

In [0]:
# Creating a Dataframe
df1 = pd.DataFrame(
    {'Names': np.array(['Apple','Bear','Cat']),
     'Scores': np.random.randint(50,100,3)
     }
     )
df1

Names  Scores
0  Apple      52
1   Bear      73
2    Cat      64

In [0]:
df1.dtypes #Closest thing to R's str()

Names     object
Scores     int64
dtype: object

In [0]:
# Two useful attributes of the DataFrame object
print(df1.index)
print(df1.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Names', 'Scores'], dtype='object')


In [0]:
# convert a two dimensional NumPy array into a DF
df2 = pd.DataFrame(np.random.rand(3,2),
             columns = ['colA','colB'])
df2

colA      colB
0  0.662338  0.286454
1  0.358689  0.443253
2  0.169733  0.690238

### Indexing with index attributes - loc and iloc and accessing rows or columns explictly with `.` method
`loc` uses the **explicit** index (ie. the actual index names) while `iloc` will use implicit (ie. the numbered positions).
`iloc` is probably the more commonly used ones as I believe most DFs don't come with proper keys...

In [0]:
# Showcasing what the difference is between explicit and implicit indexing
df3 = pd.DataFrame(np.random.rand(3,2),
             columns = ['colA','colB'],
             index = [1,2,3])
print(df3)
print(df3.loc[1]) #Calls the row named '1' in the index
print(df3.iloc[1]) #Calls the row at position 1 in the index (recall position 1 is row 2)

       colA      colB
1  0.583223  0.295335
2  0.833839  0.054124
3  0.636040  0.933769
colA    0.583223
colB    0.295335
Name: 1, dtype: float64
colA    0.833839
colB    0.054124
Name: 2, dtype: float64


In [0]:
#Access row of Series
print(series3)
print(series3.Andrew)

Andrew     90
Bryan      91
Charles    95
dtype: int64
90


In [0]:
#Access column of DF
print(df3)
print(df3.colA)

       colA      colB
1  0.583223  0.295335
2  0.833839  0.054124
3  0.636040  0.933769
1    0.583223
2    0.833839
3    0.636040
Name: colA, dtype: float64


### Indexing with filter on columns

In [0]:
df3[df3.colB > 0.9]

colA      colB
3  0.63604  0.933769

### Operating on Pandas DF

In [0]:
#My guess is that the below is like set.seed() in R
seed = np.random.RandomState(42)
op1 = pd.Series(seed.randint(0, 10, 4))
op1


0    6
1    3
2    7
3    4
dtype: int64

In [0]:
#Create a 3x4 matrix filled with random integers ranging 0-10
op2 = pd.DataFrame(seed.randint(0, 10, size = (3,4)),
                   columns = ['A','B','C','D'])
op2

A  B  C  D
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [0]:
#Showcasing that element-wise operation works on Pandas Series and DF objects
print(op1*2)
print(op2*2)

0    12
1     6
2    14
3     8
dtype: int64
    A   B   C  D
0  12   6  16  4
1   8   4  12  8
2  16  12   2  6


In [0]:
#Eg. to show Pandas is smart enough to align across objects with different indices
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
print(area)
print(population)

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64
California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64


In [0]:
population/area

### Missing data in Pandas

In [0]:
missing1 = np.array([1, None, 3, 4])
sum(missing1)

TypeError: ignored

In [0]:
#NumPy introduces a floating type missing value NaN, which is NA in R.
#Operating on NaN will always result in a NaN and does not throw an error like the native None version above.
#Importantly, NaN is only for floating point values, so there is no such thing as NaN for integers, strings or other types!!
missing2 = np.array([1, np.nan, 3, 4])
sum(missing2)

nan

In [0]:
#Handling NaN presence in arithmetic
np.nansum(missing2)

8.0

In [0]:
#Pandas is equipped to handle both `None` and `NaN`
#There are plans to add a native NA to Pandas.
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [0]:
pd.Series(['a',np.nan])

0      a
1    NaN
dtype: object

### Operating on null values
This is the equivalent is detecting or filtering for null values in R - ie. is.na(), na.omit(), replace_na()

In [0]:
missing3 = pd.DataFrame({"Names":["A","B","C"], "Scores":[1,np.nan,3]})
missing3

Names  Scores
0     A     1.0
1     B     NaN
2     C     3.0

In [0]:
#Which person has a missing Score?
#Here we use the masking method, where the boolean results act as fancy indexing
missing3[missing3.Scores.isnull()]

Names  Scores
1     B     NaN

In [0]:
#Dropping missing values
missing3.dropna()

Names  Scores
0     A     1.0
2     C     3.0

In [0]:
#Drop column instead of row, containing missing value
missing3.dropna(axis = 1)

Names
0     A
1     B
2     C

In [0]:
#dropna method has some additional arguments to trigger when to drop rows
#The threshold is the minimum number of NON-NULL values you need, before the row/column is dropped.
missing3.dropna(thresh = 1)

Names  Scores
0     A     1.0
1     B     NaN
2     C     3.0

In [0]:
#Fill missing values with single value
missing3.fillna(3)

Names  Scores
0     A     1.0
1     B     3.0
2     C     3.0

In [0]:
#Fill forward
missing3.fillna(method = "ffill")

Names  Scores
0     A     1.0
1     B     1.0
2     C     3.0

In [0]:
#Backward fill
missing3.fillna(method = "bfill")

Names  Scores
0     A     1.0
1     B     3.0
2     C     3.0

### Concatenation (or binding) of Pandas objects

In [0]:
join1 = pd.Series([1,2,3])
join2 = pd.Series([4,5,6])
print(np.concatenate([join1, join2]))

[1 2 3 4 5 6]


In [0]:
#pd.concat, the equivalent of rbind() or bind_rows() in R
join3 = pd.DataFrame({"colA":[1,2], "colB":[3,4]})
join4 = pd.DataFrame({"colA":[5,6], "colB":[7,8]})
pd.concat([join3, join4])

colA  colB
0     1     3
1     2     4
0     5     7
1     6     8

In [0]:
#pd.concat(axis = "col"), the equivalent of cbind() or bind_cols() in R
join5 = pd.DataFrame({"colA":[1,2], "colB":[3,4]})
join6 = pd.DataFrame({"colC":[5,6], "colD":[7,8]})
pd.concat([join5, join6], axis = 1)

colA  colB  colC  colD
0     1     3     5     7
1     2     4     6     8

### Merge and Join datasets

In [0]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [0]:
#Pandas has a very simple merge function to join tables
pd.merge(df1, df2)

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [0]:
#What if the joining key has a different column name across both tables? For eg:
#While it works, its not as elegant as in R with the `by = c('left' = 'right')` specification
#You'll find a redundant column `emp` left in the table
df3 = pd.DataFrame({'emp': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(pd.merge(df1, df3, left_on="employee", right_on="emp"))
#Adding one more function `drop()` to drop the redundant column. So much typing!
print(pd.merge(df1, df3, left_on="employee", right_on="emp").drop("emp", axis = 1))

  employee        group   emp  hire_date
0      Bob   Accounting   Bob       2008
1     Jake  Engineering  Jake       2012
2     Lisa  Engineering  Lisa       2004
3      Sue           HR   Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [0]:
#Inner, left, right joins
#Equivalent in R: inner_join, left_join, right_join
df4 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df5 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
print(df4)
print(df5)
print("Inner join")
print(pd.merge(df4, df5, how = "inner"))
print("Left join")
print(pd.merge(df4, df5, how = "left"))
print("Right join")
print(pd.merge(df4, df5, how = "right"))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
Inner join
   name   food drink
0  Mary  bread  wine
Left join
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine
Right join
     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer


### Grouping and aggregation

In [0]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [0]:
planets.method.drop_duplicates()

0                    Radial Velocity
29                           Imaging
32         Eclipse Timing Variations
91                           Transit
113                       Astrometry
680        Transit Timing Variations
787    Orbital Brightness Modulation
902                     Microlensing
941                    Pulsar Timing
958      Pulsation Timing Variations
Name: method, dtype: object

In [0]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [0]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [0]:
#THe result looks just like an excel spreadsheet with merged cells!
agg1 = planets.groupby('method').aggregate([np.median, np.sum])
agg1

number       ...    year         
                              median  sum  ...  median      sum
method                                     ...                 
Astrometry                         1    2  ...  2011.5     4023
Eclipse Timing Variations          2   15  ...  2010.0    18090
Imaging                            1   50  ...  2009.0    76347
Microlensing                       1   27  ...  2010.0    46225
Orbital Brightness Modulation      2    5  ...  2011.0     6035
Pulsar Timing                      3   11  ...  1994.0     9992
Pulsation Timing Variations        1    1  ...  2007.0     2007
Radial Velocity                    1  952  ...  2009.0  1110158
Transit                            1  776  ...  2012.0   798461
Transit Timing Variations          2    9  ...  2012.5     8050

[10 rows x 10 columns]

In [0]:
#Trying to index this result
agg1.loc["Astrometry"]

number          median       1.000
                sum          2.000
orbital_period  median     631.180
                sum       1262.360
mass            median         NaN
                sum          0.000
distance        median      17.875
                sum         35.750
year            median    2011.500
                sum       4023.000
Name: Astrometry, dtype: float64

In [0]:
agg1.iloc[0,0]

1

In [0]:
agg1.loc["Imaging","mass"]

median    NaN
sum       0.0
Name: Imaging, dtype: float64

In [0]:
#This 'stack' method makes the excel sheet thingy look easier to read!
agg1.stack()

number  ...       year
method                                        ...           
Astrometry                    median       1  ...     2011.5
                              sum          2  ...     4023.0
Eclipse Timing Variations     median       2  ...     2010.0
                              sum         15  ...    18090.0
Imaging                       median       1  ...     2009.0
                              sum         50  ...    76347.0
Microlensing                  median       1  ...     2010.0
                              sum         27  ...    46225.0
Orbital Brightness Modulation median       2  ...     2011.0
                              sum          5  ...     6035.0
Pulsar Timing                 median       3  ...     1994.0
                              sum         11  ...     9992.0
Pulsation Timing Variations   median       1  ...     2007.0
                              sum          1  ...     2007.0
Radial Velocity               median       1  ...     2009.0
                              sum        952  ...  1110158.0
Transit                       median       1  ...     2012.0
                              sum        776  ...   798461.0
Transit Timing Variations     median       2  ...     2012.5
                              sum          9  ...     8050.0

[20 rows x 5 columns]

In [0]:
#This is also another version of a pivot, but the representation doesn't make sense...
agg1.unstack()

                method                       
number  median  Astrometry                             1.0
                Eclipse Timing Variations              2.0
                Imaging                                1.0
                Microlensing                           1.0
                Orbital Brightness Modulation          2.0
                                                   ...    
year    sum     Pulsar Timing                       9992.0
                Pulsation Timing Variations         2007.0
                Radial Velocity                  1110158.0
                Transit                           798461.0
                Transit Timing Variations           8050.0
Length: 100, dtype: float64

In [0]:
agg1.stack().dtypes

number              int64
orbital_period    float64
mass              float64
distance          float64
year              float64
dtype: object

In [0]:
#Using a dictionary to map column names to the aggregate function we want to apply
planets.groupby('method').aggregate({'number':np.nanmin, 'distance':np.sum})

number   distance
method                                          
Astrometry                          1      35.75
Eclipse Timing Variations           1    1261.44
Imaging                             1    2166.91
Microlensing                        1   41440.00
Orbital Brightness Modulation       1    2360.00
Pulsar Timing                       1    1200.00
Pulsation Timing Variations         1       0.00
Radial Velocity                     1   27348.11
Transit                             1  134242.77
Transit Timing Variations           2    3313.00